### ISSUE TITLE
요청을

### ISSUE THREAD

**Issue by hmdzl001** [Sharku2011/GirlsFrontline-pixel-dungeon#30]
Dear developers of girlsfrontline pixel dungeon:
I'm the SPS-PD's developer developer. I have played your game yesterday and I found some picture in you game is... beautiful. I want use some of them in my mod so I come here for your   permission. Thank you.

**Comment by Sharku2011** [comment]
We have reviewed your proposal and unfortunately we can not accept your request. First of all, the right to a graphics resource belongs to a partner, not me, and he does not want to share his own resources.

**Comment by Sharku2011** [comment]
But if you specify what picture you need, he is willing to reconsider it again

**Comment by hmdzl001** [comment]
Well, I only need item.png. I know nothing about girlfrontline I don't think those npc and mobs is useful in my mod. 
But if, I mean if, I use any picture(including item.png) in your mod, I will add one(or more) developer npc in town just like other developer who had help me on my mod. You and your partner can choose what that npcs looks like and which thing they talking about.
