### ISSUE TITLE
PD wiki page

### ISSUE THREAD

**Issue by egoal** [Sharku2011/GirlsFrontline-pixel-dungeon#31]
hi, not a issue, but i just want to inform you,  [kostis12345](https://www.reddit.com/user/kostis12345/) create a wiki for your mod: https://pixeldungeon.fandom.com/wiki/Mod-Girls_Frontline_Pixel_Dungeon

check it if youre interested, and sorry for bother.

btw, i am the developer of the mod [Darkest Pixel Dungeon](https://github.com/egoal/darkest-pixel-dungeon). :-)

**Comment by Sharku2011** [comment]
Thanks four your information 😄 
We are planning release a new build to upload for Google PlayStore, so I'm too busy to contribute wiki page now😢.

Anyway, thanks four your help.

**Comment by egoal** [comment]
hi, wiki maintainer kostis12345 create a page about developers. yes, I need you help. here is the page:
https://pixeldungeon.fandom.com/wiki/Mod_Developers

he want to cite your work but cannot find your contact information, the email is hidden by default on github. 
anyway, "is some kind of address for players to give feedback to developers: it can be an email / a social media profile" by kostis, check it if you are interested.

and, not an issue again..
