### ISSUE TITLE
about herosprite

### ISSUE THREAD

**Issue by Moekey114514** [Sharku2011/GirlsFrontline-pixel-dungeon#32]
not a issue.
I'm a newbie in pd developing. I draw a herosprite with 24 x 24 like GFdungeon did but I found that is too big in map. When I use mirrorscroll , those fake hero will looks like step on my head. Sometimes a mob will do so .

It confused me for a long time and I come here for your help please.

**Comment by Sharku2011** [comment]
The original Pixel Dungeon hardcoded the size-related variables to 16 in the tilemap rendering code. If you want to change the size, you have to find and fix the relevant variables one by one, and it will be not as easy as it was for me.

**Comment by Sharku2011** [comment]
솔직히 말하자면, 온전하게 부작용 없이 타일맵 사이즈를 변경하는데 실패했으며, 그건 아직 R&D 상태입니다.

**Comment by Moekey114514** [comment]
but how do GFPD fix this ?  GFPD is using 24 x 24 sprite but the size in game is same as 16 like originalPD.

**Comment by Moekey114514** [comment]
okey. I'll make my sprite smaller in order to avoid a mirrorhero step on my head. thanks for your answer. GFPD is my favorite PDmod .sincerely thanks to you for your masterpiece  ;D
